### ISSUE TITLE
Fallo na implementacion de ServidorRespaldo: valor nulo

### ISSUE THREAD

**Issue by lauramcastro** [borjargz/PracticaVVS#11]
A existencia de un constructor que non da valor ao servidorRespaldo, significa que se poden construir obxectos desta clase que non teñan ningún servidor de respaldo (inicialización por defecto a null). Isto contradi a especificación, e provocaría un NullPointerException no caso de executar o método buscar e non se atopen resultados.

**Comment by borjargz** [comment]
Corregido, eliminado el constructor.
