### ISSUE TITLE
Fallo na implementación de Anuncio: obtenerListaDeReproducción

### ISSUE THREAD

**Issue by lauramcastro** [borjargz/PracticaVVS#13]
Cada vez que se solicita a lista de reproducción de un anuncio, o anuncio é engadido ao á colección que se devolve, de xeito que sucesivas chamadas ao mesmo método van devolvendo coleccións co anuncio repetido 2, 3, 4... veces (tantas como invocacións se realizaran ao método).

**Comment by borjargz** [comment]
Se comprueba si se ha añadido el elemento antes de volver a añadirlo.
