### ISSUE TITLE
Fallo na implementación de Anuncio: buscar

### ISSUE THREAD

**Issue by lauramcastro** [borjargz/PracticaVVS#14]
Cada vez que se realiza unha búsqueda que coincide co título, o anuncio é engadido ao á colección que se devolve, de xeito que sucesivas chamadas ao mesmo método van devolvendo coleccións co anuncio repetido 2, 3, 4... veces (tantas como invocacións se realizaran ao método).

**Comment by borjargz** [comment]
Se comprueba si el anuncio ya se ha añadido, para no añadirlo de nuevo.
