### ISSUE TITLE
Fallo na implementación de Canción: obtenerListaDeReproducción

### ISSUE THREAD

**Issue by lauramcastro** [borjargz/PracticaVVS#15]
Cada vez que se solicita a lista de reproducción de unha canción, a canción é engadida á colección que se devolve, de xeito que sucesivas chamadas ao mesmo método van devolvendo coleccións coa canción repetida 2, 3, 4... veces (tantas como invocacións se realizaran ao método).

**Comment by borjargz** [comment]
duplicado, #issue 13
