### ISSUE TITLE
Fallo na implementación de Canción: buscar

### ISSUE THREAD

**Issue by lauramcastro** [borjargz/PracticaVVS#16]
Cada vez que se realiza unha búsqueda que coincide co título, a canción é engadida á colección que se devolve, de xeito que sucesivas chamadas ao mesmo método van devolvendo coleccións coa canción repetida 2, 3, 4... veces (tantas como invocacións se realizaran ao método).

**Comment by borjargz** [comment]
Se comprueba si se ha añadido ya la cancion para evitar añadirla de nuevo.
