### ISSUE TITLE
Reubicación da documentación.

### ISSUE THREAD

**Issue by lauramcastro** [borjargz/PracticaVVS#2]
Xeras JavaDoc, pero non deberias subirla ao repositorio: lembra, todo que se poida xerar, non debería estar ocupando sitio nun repositorio, e ter que descargarse/compararse cada vez que nos comunicamos cunha copia remota do mesmo. O diagrama UML debería estar nun subdirectorio da carpeta doc.

**Comment by borjargz** [comment]
Eliminado el javadoc del repositorio.
