### ISSUE TITLE
Inconsistencia na nomenclatura de métodos

### ISSUE THREAD

**Issue by lauramcastro** [borjargz/PracticaVVS#8]
Os métodos da interface Servidor no diagrama UML respectan o camelCase do enunciado (que é consistente coas normas de estilo en Java: empezar con minúscula e alternar con Maiúsculas ao principio de cada palabra, por exemplo: obtenerNombre). Porén, na interface Servidor implementada (e polo tanto nas súas implementacións ServidorGenerico e ServidorRespaldo, cambiouse o estilo de nomeado (empezando con maiúscula) nalgúns casos.

**Comment by borjargz** [comment]
Todo refactorizado a camelCase.
