### ISSUE TITLE
Vulnerabilidad na implementación de ServidorGenérico: agregar

### ISSUE THREAD

**Issue by lauramcastro** [borjargz/PracticaVVS#9]
O método agregar en ServidorGenérico, comproba primeiro se o contido agregar existe ou non, antes de comprobar se o token é o token de administrador.

Isto significa que, sen ter un token de administrador, nin sequera un token válido, se podería empregar o método agregar para obter información dos contidos almacenados nos servidor: enviando peticións e examinando para cales delas o servidor lanza unha excepción de DuplicateContent poderiamos coñecer esa información que debería ser "privilexiada" (para iso se pide o token de administrador).

**Comment by borjargz** [comment]
Corregido, comprobando primero si el token es de administrador.

**Comment by lauramcastro** [comment]
Mellora: a solución introducida é boa, pero na firma do método permanece a TokenNotFoundException, a pesar de que esa excepción non se lanza nunca.
